// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcQaaDsvtux5B0O4cEFpg9B0p6QIKVzM',
    appId: '1:1070945266056:web:9f26e5e7ac294f6a48b23d',
    messagingSenderId: '1070945266056',
    projectId: 'studyapp-17b6a',
    authDomain: 'studyapp-17b6a.firebaseapp.com',
    storageBucket: 'studyapp-17b6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fGLRMRXyGl_Ge2gjY4_6CnQPtNOQYOY',
    appId: '1:1070945266056:android:5b4d9776b01a79d048b23d',
    messagingSenderId: '1070945266056',
    projectId: 'studyapp-17b6a',
    storageBucket: 'studyapp-17b6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnt6T-YH_J3baNAAu-w8ToNTevenb-4Lg',
    appId: '1:1070945266056:ios:fc9cd71017af626e48b23d',
    messagingSenderId: '1070945266056',
    projectId: 'studyapp-17b6a',
    storageBucket: 'studyapp-17b6a.appspot.com',
    iosClientId:
        '1070945266056-vq3k08v8o0lm627v79pjnr998ddddg5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnt6T-YH_J3baNAAu-w8ToNTevenb-4Lg',
    appId: '1:1070945266056:ios:fc9cd71017af626e48b23d',
    messagingSenderId: '1070945266056',
    projectId: 'studyapp-17b6a',
    storageBucket: 'studyapp-17b6a.appspot.com',
    iosClientId:
        '1070945266056-vq3k08v8o0lm627v79pjnr998ddddg5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
